# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='name',
        ),
    ]
